export const useActiEleves = () => {
    const datatest = useState('actiEleves', () => [])
    
    const exec = async () => {
        const req = await useFetch('https://api.npoint.io/275683f062ca07a29b1c')
        datatest.value = req.data
    }
    
    exec()
    
    return datatest
}

export const useBibli = () => {
    const datatest = useState('bibli', () => [])
    const headers = useRequestHeaders(['cookie'])
    const exec = async () => {
        const req = await useFetch('https://capytaledev.ac-paris.fr/web/export?_=1688922855351', { headers })
        console.log(req)
        datatest.value = req.data
    }
    
    exec()
    
    return datatest
}


export const useActivites = () => useState('typeActivites', () => [
    {
      "id": "codabloc",
      "name": "Codabloc",
      "fav": true,
      "fullName": "Codabloc",
      "description": "L'environnement Scratch intégré dans Capytale pour apprendre à programmer avec des blocs.",
      "summary": "",
      "icon": {
        "path": "/web/modules/custom/capytale_activity/src/Activity/logo/logo_codabloc.svg",
        "style": {
          "color": "#898dc5",
          "background-color": "#ffffff"
        }
      },
      "category": {
        "all": 10,
        "ecole": 1,
        "college": 1,
        "lycee": 5
      },
      "helpUrl": "https://capytale2.ac-paris.fr/wiki/doku.php?id=codabloc",
      "bundle": "activity"
    },
    {
      "id": "codepuzzle",
      "name": "Code Puzzle",
      "fullName": "Code Puzzle",
      "description": "Générateur et gestionnare de puzzles de Parsons.",
      "summary": "",
      "icon": {
        "path": "/web/modules/custom/capytale_activity/src/Activity/logo/logo_codabloc.svg",
        "style": {
          "color": "#79c824",
          "background-color": "#ffffff"
        }
      },
      "category": {
        "all": 10,
        "ecole": 1,
        "college": 3,
        "lycee": 7
      },
      "helpUrl": "https://capytale2.ac-paris.fr/wiki/doku.php?id=codepuzzle",
      "bundle": "activity"
    },
    {
      "id": "console.python3",
      "name": "Script-Console",
      "beta": true,
      "fullName": "Script-Console",
      "description": "L'environnement classique de programmation : un script Python à gauche et une console d'exécution à droite.",
      "summary": "",
      "icon": {
        "path": "/web/modules/custom/capytale_activity/src/Activity/logo/logo_console.svg",
        "style": {
          "color": "#000000",
          "background-color": "#ffffff"
        }
      },
      "category": {
        "all": 10,
        "college": 30,
        "lycee": -1,
        "prepa": 1000
      },
      "helpUrl": "https://capytale2.ac-paris.fr/wiki/doku.php",
      "bundle": "console_activity"
    },
    {
      "id": "geogebra",
      "name": "GeoGebra",
      "beta": true,
      "fullName": "GeoGebra",
      "description": "Géométrie dynamique avec Geogebra enrichi des fonctionnalités pédagogiques de Capytale.",
      "summary": "",
      "icon": {
        "path": "/web/modules/custom/capytale_activity/src/Activity/logo/logo_geogebra.svg",
        "style": {
          "color": "#9999ff",
          "background-color": "#ffffff"
        }
      },
      "category": {
        "all": 10,
        "ecole": 1,
        "college": 1,
        "lycee": 5
      },
      "helpUrl": "https://capytale2.ac-paris.fr/wiki/doku.php?id=geogebra",
      "bundle": "activity"
    },
    {
      "id": "html",
      "name": "HTML/CSS/JS",
      "fullName": "HTML/CSS/JS",
      "description": "Découvrir les langaes du Web : html, CSS et JavaScript.",
      "summary": "",
      "icon": {
        "path": "/web/modules/custom/capytale_activity/src/Activity/logo/logo_html.svg",
        "style": {
          "color": "#0b5394",
          "background-color": "#ffffff"
        }
      },
      "category": {
        "all": 10,
        "college": 10,
        "lycee": 3
      },
      "helpUrl": "https://capytale2.ac-paris.fr/wiki/doku.php?id=html",
      "bundle": "activity"
    },
    {
      "id": "notebook.ocaml",
      "name": "OCaml",
      "fullName": "Notebook OCaml",
      "description": "Le langage OCaml dans un notebook.",
      "summary": "",
      "icon": {
        "path": "/web/modules/custom/capytale_activity/src/Activity/logo/logo_ocaml.svg",
        "style": {
          "color": "#de7932",
          "background-color": "#ffffff"
        }
      },
      "category": {
        "all": 10,
        "prepa": 5
      },
      "helpUrl": "https://capytale2.ac-paris.fr/p/basthon/n/?id=330758&kernel=ocaml",
      "bundle": "notebook_activity"
    },
    {
      "id": "notebook.python3",
      "name": "Notebook",
      "fullName": "Notebook Python",
      "description": "Python dans un notebook Jupyter : une alternance de cellules de texte riche et de cellules de code exécutables.",
      "summary": "",
      "icon": {
        "path": "/web/modules/custom/capytale_activity/src/Activity/logo/logo_nb.svg",
        "style": {
          "color": "#ff6402",
          "background-color": "#ffffff"
        }
      },
      "category": {
        "all": 10,
        "college": 30,
        "lycee": -1,
        "prepa": 1000
      },
      "helpUrl": "https://capytale2.ac-paris.fr/wiki/doku.php?id=notebook",
      "bundle": "notebook_activity"
    },
    {
      "id": "notebook.sql",
      "name": "SQL",
      "fullName": "Notebook SQL",
      "description": "Le langage SQL dans un notebook.",
      "summary": "",
      "icon": {
        "path": "/web/modules/custom/capytale_activity/src/Activity/logo/logo_sql.svg",
        "style": {
          "color": "#f1c232",
          "background-color": "#ffffff"
        }
      },
      "category": {
        "all": 10,
        "college": 30,
        "lycee": -1,
        "prepa": 1000
      },
      "helpUrl": "https://capytale2.ac-paris.fr/p/basthon/n/?id=42529&kernel=sql",
      "bundle": "notebook_activity"
    },
    {
      "id": "pixel",
      "name": "Pixel Art",
      "fullName": "Pixel Art",
      "description": "Construire un dessin pixelisé avec des blocs de code.",
      "summary": "",
      "icon": {
        "path": "/web/modules/custom/capytale_activity/src/Activity/logo/logo_pixel.svg",
        "style": {
          "color": "#898dc5",
          "background-color": "#ffffff"
        }
      },
      "category": {
        "all": 10,
        "ecole": 1,
        "college": 1,
        "lycee": 5
      },
      "helpUrl": "https://capytale2.ac-paris.fr/wiki/doku.php?id=codabloc",
      "bundle": "activity"
    }
  ])

export const useTags = () => {
    const tags = ref([
        {
            "tagID": "1",
            "tagColor": "red",
            "label": "SNT"
        },
        {
            "tagID": "2",
            "tagColor": "orange",
            "label": "NSI"
        },
        {
            "tagID": "3",
            "tagColor": "amber",
            "label": "Corrigé"
        },
        {
            "tagID": "4",
            "tagColor": "yellow",
            "label": "Pas Corrigé"
        },
    ])
    return tags
}

export const useActiTags = () => {
    const actiTags = ref([
        {
            "nid": "1325993",
            "tid": ["1", "2"]
        },
        {
            "nid": "1335649",
            "tid": ["1", "2"]
        },
        {
            "nid": "1335679",
            "tid": ["1", "2"]
        },
        {
            "nid": "1335859",
            "tid": ["1", "2"]
        },
        {
            "nid": "1366390",
            "tid": ["1", "2"]
        },
        {
            "nid": "1394485",
            "tid": ["1", "2"]
        },
        {
            "nid": "1435331",
            "tid": ["1", "2"]
        },
        {
            "nid": "1442499",
            "tid": ["1", "2"]
        },
        {
            "nid": "1454256",
            "tid": ["1", "2"]
        },
        {
            "nid": "1499408",
            "tid": ["1", "2"]
        },
        {
            "nid": "1527496",
            "tid": ["1", "2"]
        },
    ])

    return actiTags
}
export const useFiles = () => {
    const acti = ref([
        {
            "nid": "1325993",
            "changed": "1681564124",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Recrutement d\u0027un joueur de basket",
            "aid": "1325993",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1325993",
            "workflow": "0",
            "code": "eb04-1325993",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-02-02T21:03:57",
            "tr_end": "2023-03-04T21:03:57",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1325993:0",
            "views_total": 69,
            "views_hidden": 0,
            "tags": {
                "nid": "1325993",
                "tids": "423012,463417",
                "names": "NSI,Corrig\u00e9",
                "colors": "#9A9CFF,#F83A22"
            },
            "row_id": "row-1325993",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1681564124",
            "player": "activity_access\/1325993",
            "note": "Note relative au joueur de basket"
        },
        {
            "nid": "1335649",
            "changed": "1681563821",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Algorithmes gloutons : rendu de monnaie",
            "aid": "1335649",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1335649",
            "workflow": "0",
            "code": "55d1-1335649",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-02-05T22:52:02",
            "tr_end": "2023-03-07T22:52:02",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1335649:0",
            "views_total": 72,
            "views_hidden": 0,
            "tags": {
                "nid": "1335649",
                "tids": "423012,463417",
                "names": "NSI,Corrig\u00e9",
                "colors": "#9A9CFF,#F83A22"
            },
            "row_id": "row-1335649",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1681563821",
            "player": "activity_access\/1335649",
            "note": "Notes relatives au rendu de monnaie"
        },
        {
            "nid": "1335679",
            "changed": "1681564071",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Recherche dichotomique",
            "aid": "1335679",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1335679",
            "workflow": "0",
            "code": "1100-1335679",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-02-05T23:02:58",
            "tr_end": "2023-03-07T23:02:58",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1335679:0",
            "views_total": 65,
            "views_hidden": 2,
            "tags": {
                "nid": "1335679",
                "tids": "423012,463417",
                "names": "NSI,Corrig\u00e9",
                "colors": "#9A9CFF,#F83A22"
            },
            "row_id": "row-1335679",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1681564071",
            "player": "activity_access\/1335679"
        },
        {
            "nid": "1335859",
            "changed": "1685011767",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Technique du fond vert",
            "aid": "1335859",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1335859",
            "workflow": "0",
            "code": "8c96-1335859",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2022-05-18T15:06:19",
            "tr_end": "2022-06-17T15:06:19",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1335859:0",
            "views_total": 190,
            "views_hidden": 0,
            "tags": {
                "nid": "1335859",
                "tids": "423012,423016",
                "names": "NSI,SNT",
                "colors": "#9A9CFF,#92E1C0"
            },
            "row_id": "row-1335859",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685011767",
            "player": "activity_access\/1335859"
        },
        {
            "nid": "1366390",
            "changed": "1685730870",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "D\u00e9couverte du Markdown",
            "aid": "1366390",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1366390",
            "workflow": "0",
            "code": "fd1d-1366390",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-02-12T10:00:24",
            "tr_end": "2023-03-14T10:00:24",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1366390:0",
            "views_total": 69,
            "views_hidden": 0,
            "tags": {
                "nid": "1366390",
                "tids": "423016,463417",
                "names": "SNT,Corrig\u00e9",
                "colors": "#92E1C0,#F83A22"
            },
            "row_id": "row-1366390",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685730870",
            "player": "activity_access\/1366390"
        },
        {
            "nid": "1394485",
            "changed": "1684957684",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Markdown algorithmes",
            "aid": "1394485",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1394485",
            "workflow": "0",
            "code": "6f19-1394485",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-02-27T15:04:11",
            "tr_end": "2023-03-29T15:04:11",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1394485:0",
            "views_total": 71,
            "views_hidden": 0,
            "tags": {
                "nid": "1394485",
                "tids": "423012,463417,471584",
                "names": "NSI,Corrig\u00e9,\u00e0 corriger",
                "colors": "#9A9CFF,#F83A22,#16A765"
            },
            "row_id": "row-1394485",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1684957684",
            "player": "activity_access\/1394485"
        },
        {
            "nid": "1435331",
            "changed": "1685631348",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Donn\u00e9es au format CSV",
            "aid": "1435331",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1435331",
            "workflow": "0",
            "code": "2e7f-1435331",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-03-08T19:09:09",
            "tr_end": "2023-04-07T19:09:09",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1435331:0",
            "views_total": 92,
            "views_hidden": 0,
            "tags": {
                "nid": "1435331",
                "tids": "423016",
                "names": "SNT",
                "colors": "#92E1C0"
            },
            "row_id": "row-1435331",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685631348",
            "player": "activity_access\/1435331"
        },
        {
            "nid": "1442499",
            "changed": "1685062339",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Manipulation du format CSV",
            "aid": "1442499",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1442499",
            "workflow": "0",
            "code": "568c-1442499",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-03-09T22:31:52",
            "tr_end": "2023-04-08T22:31:52",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1442499:0",
            "views_total": 77,
            "views_hidden": 0,
            "tags": {
                "nid": "1442499",
                "tids": "423012,471584",
                "names": "NSI,\u00e0 corriger",
                "colors": "#9A9CFF,#16A765"
            },
            "row_id": "row-1442499",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685062339",
            "player": "activity_access\/1442499"
        },
        {
            "nid": "1454256",
            "changed": "1685543214",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Donn\u00e9es en tables : D\u00e9couverte de SQL",
            "aid": "1454256",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1454256",
            "workflow": "0",
            "code": "973b-1454256",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2022-03-19T11:22:05",
            "tr_end": "2022-04-18T11:22:05",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.sql",
            "bib": "1454256:0",
            "views_total": 123,
            "views_hidden": 0,
            "tags": {
                "nid": "1454256",
                "tids": "423012,423016",
                "names": "NSI,SNT",
                "colors": "#9A9CFF,#92E1C0"
            },
            "row_id": "row-1454256",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_sql.svg",
            "provider": "hdf",
            "last_access": "1685543214",
            "player": "activity_access\/1454256"
        },
        {
            "nid": "1499408",
            "changed": "1685540624",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Lecture de fichiers au format CSV",
            "aid": "1499408",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1499408",
            "workflow": "0",
            "code": "d806-1499408",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-03-23T21:23:24",
            "tr_end": "2023-04-22T21:23:24",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1499408:0",
            "views_total": 95,
            "views_hidden": 0,
            "tags": {
                "nid": "1499408",
                "tids": "423012,463417",
                "names": "NSI,Corrig\u00e9",
                "colors": "#9A9CFF,#F83A22"
            },
            "row_id": "row-1499408",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685540624",
            "player": "activity_access\/1499408"
        },
        {
            "nid": "1527496",
            "changed": "1685540643",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Inventaire d\u0027un hypermarch\u00e9 (lecture et \u00e9criture d\u0027un fichier au format CSV)",
            "aid": "1527496",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1527496",
            "workflow": "0",
            "code": "07fe-1527496",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-03-30T17:30:52",
            "tr_end": "2023-04-29T17:30:52",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1527496:0",
            "views_total": 38,
            "views_hidden": 0,
            "tags": {
                "nid": "1527496",
                "tids": "423012,463417",
                "names": "NSI,Corrig\u00e9",
                "colors": "#9A9CFF,#F83A22"
            },
            "row_id": "row-1527496",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685540643",
            "player": "activity_access\/1527496"
        },
        {
            "nid": "1533637",
            "changed": "1685782380",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Traiter des donn\u00e9es avec Python",
            "aid": "1533637",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1533637",
            "workflow": "0",
            "code": "4247-1533637",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2022-05-24T07:22:16",
            "tr_end": "2022-06-23T07:22:16",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1533637:0",
            "views_total": 71,
            "views_hidden": 0,
            "tags": {
                "nid": "1533637",
                "tids": "423016,463417",
                "names": "SNT,Corrig\u00e9",
                "colors": "#92E1C0,#F83A22"
            },
            "row_id": "row-1533637",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685782380",
            "player": "activity_access\/1533637"
        },
        {
            "nid": "1533651",
            "changed": "1685540647",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "CSV : Fusion de tables",
            "aid": "1533651",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1533651",
            "workflow": "0",
            "code": "1647-1533651",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-04-02T19:41:56",
            "tr_end": "2023-05-02T19:41:56",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1533651:0",
            "views_total": 80,
            "views_hidden": 0,
            "tags": {
                "nid": "1533651",
                "tids": "423012,463417",
                "names": "NSI,Corrig\u00e9",
                "colors": "#9A9CFF,#F83A22"
            },
            "row_id": "row-1533651",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685540647",
            "player": "activity_access\/1533651"
        },
        {
            "nid": "1536931",
            "changed": "1685730789",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Lecture de fichiers au format CSV",
            "aid": "1536931",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1536931",
            "workflow": "0",
            "code": "3889-1536931",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-04-03T10:05:09",
            "tr_end": "2023-05-03T10:05:09",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1536931:0",
            "views_total": 74,
            "views_hidden": 0,
            "tags": {
                "nid": "1536931",
                "tids": "423016,463417",
                "names": "SNT,Corrig\u00e9",
                "colors": "#92E1C0,#F83A22"
            },
            "row_id": "row-1536931",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685730789",
            "player": "activity_access\/1536931"
        },
        {
            "nid": "1544299",
            "changed": "1685540629",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Inventaire d\u0027un hypermarch\u00e9 1\/3",
            "aid": "1544299",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1544299",
            "workflow": "0",
            "code": "0706-1544299",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-03-30T17:30:52",
            "tr_end": "2023-04-29T17:30:52",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1544299:0",
            "views_total": 54,
            "views_hidden": 0,
            "tags": {
                "nid": "1544299",
                "tids": "423012,463417",
                "names": "NSI,Corrig\u00e9",
                "colors": "#9A9CFF,#F83A22"
            },
            "row_id": "row-1544299",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685540629",
            "player": "activity_access\/1544299"
        },
        {
            "nid": "1544335",
            "changed": "1685540637",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Inventaire d\u0027un hypermarch\u00e9 2\/3",
            "aid": "1544335",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1544335",
            "workflow": "0",
            "code": "d930-1544335",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-03-30T17:30:52",
            "tr_end": "2023-04-29T17:30:52",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1544335:0",
            "views_total": 49,
            "views_hidden": 0,
            "tags": {
                "nid": "1544335",
                "tids": "423012,463417",
                "names": "NSI,Corrig\u00e9",
                "colors": "#9A9CFF,#F83A22"
            },
            "row_id": "row-1544335",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685540637",
            "player": "activity_access\/1544335"
        },
        {
            "nid": "1544441",
            "changed": "1685540633",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Inventaire d\u0027un hypermarch\u00e9 3\/3",
            "aid": "1544441",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1544441",
            "workflow": "0",
            "code": "4ce4-1544441",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-03-30T17:30:52",
            "tr_end": "2023-04-29T17:30:52",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1544441:0",
            "views_total": 48,
            "views_hidden": 0,
            "tags": {
                "nid": "1544441",
                "tids": "423012,463417",
                "names": "NSI,Corrig\u00e9",
                "colors": "#9A9CFF,#F83A22"
            },
            "row_id": "row-1544441",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685540633",
            "player": "activity_access\/1544441"
        },
        {
            "nid": "1551637",
            "changed": "1684950591",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Correction : Inventaire d\u0027un hypermarch\u00e9",
            "aid": "1551637",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1551637",
            "workflow": "0",
            "code": "123e-1551637",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-03-30T17:30:52",
            "tr_end": "2023-04-29T17:30:52",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1551637:0",
            "views_total": 48,
            "views_hidden": 0,
            "tags": {
                "nid": "1551637",
                "tids": "423012",
                "names": "NSI",
                "colors": "#9A9CFF"
            },
            "row_id": "row-1551637",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1684950591",
            "player": "activity_access\/1551637"
        },
        {
            "nid": "1613028",
            "changed": "1684162680",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "architecture von Neumann",
            "aid": "1613028",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1613028",
            "workflow": "0",
            "code": "1d3d-1613028",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-05-02T12:36:51",
            "tr_end": "2023-06-01T12:36:51",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1613028:0",
            "views_total": 73,
            "views_hidden": 0,
            "tags": {
                "nid": "1613028",
                "tids": "423016",
                "names": "SNT",
                "colors": "#92E1C0"
            },
            "row_id": "row-1613028",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1684162680",
            "player": "activity_access\/1613028"
        },
        {
            "nid": "1618173",
            "changed": "1685730602",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Impact environnemental des centres de donn\u00e9es",
            "aid": "1618173",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1618173",
            "workflow": "0",
            "code": "d879-1618173",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-05-03T22:57:19",
            "tr_end": "2023-06-02T22:57:19",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1618173:0",
            "views_total": 115,
            "views_hidden": 0,
            "tags": {
                "nid": "1618173",
                "tids": "423016,463417",
                "names": "SNT,Corrig\u00e9",
                "colors": "#92E1C0,#F83A22"
            },
            "row_id": "row-1618173",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685730602",
            "player": "activity_access\/1618173"
        },
        {
            "nid": "1618177",
            "changed": "1685731014",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Informatique en nuage",
            "aid": "1618177",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1618177",
            "workflow": "0",
            "code": "9f0f-1618177",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-05-03T23:19:26",
            "tr_end": "2023-06-02T23:19:26",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1618177:0",
            "views_total": 95,
            "views_hidden": 0,
            "tags": {
                "nid": "1618177",
                "tids": "423016,463417",
                "names": "SNT,Corrig\u00e9",
                "colors": "#92E1C0,#F83A22"
            },
            "row_id": "row-1618177",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685731014",
            "player": "activity_access\/1618177"
        },
        {
            "nid": "1630975",
            "changed": "1683588035",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Correction : Fusion de tables",
            "aid": "1630975",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1630975",
            "workflow": "0",
            "code": "25a8-1630975",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-04-02T19:41:56",
            "tr_end": "2023-05-02T19:41:56",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1630975:0",
            "views_total": 0,
            "views_hidden": 0,
            "tags": {
                "nid": "1630975",
                "tids": "423012",
                "names": "NSI",
                "colors": "#9A9CFF"
            },
            "row_id": "row-1630975",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1683588035",
            "player": "activity_access\/1630975"
        },
        {
            "nid": "1631047",
            "changed": "1684961731",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Portes logiques",
            "aid": "1631047",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1631047",
            "workflow": "0",
            "code": "c1e6-1631047",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-05-08T21:40:56",
            "tr_end": "2023-06-07T21:40:56",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1631047:0",
            "views_total": 50,
            "views_hidden": 0,
            "tags": {
                "nid": "1631047",
                "tids": "423012",
                "names": "NSI",
                "colors": "#9A9CFF"
            },
            "row_id": "row-1631047",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1684961731",
            "player": "activity_access\/1631047"
        },
        {
            "nid": "1631071",
            "changed": "1683640509",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Portes logiques et expressions bool\u00e9ennes (Activit\u00e9 bool\u00e9ens 1)",
            "aid": "1631071",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1631071",
            "workflow": "0",
            "code": "6147-1631071",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": null,
            "tr_end": null,
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1631071:0",
            "views_total": 13,
            "views_hidden": 0,
            "tags": {
                "nid": "1631071",
                "tids": "423012",
                "names": "NSI",
                "colors": "#9A9CFF"
            },
            "row_id": "row-1631071",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1683640509",
            "player": "activity_access\/1631071"
        },
        {
            "nid": "1642069",
            "changed": "1685612046",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Cartographie 1",
            "aid": "1642069",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1642069",
            "workflow": "0",
            "code": "c466-1642069",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2022-01-22T09:10:38",
            "tr_end": "2022-02-21T09:10:38",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1642069:0",
            "views_total": 85,
            "views_hidden": 0,
            "tags": {
                "nid": "1642069",
                "tids": "423016,463417",
                "names": "SNT,Corrig\u00e9",
                "colors": "#92E1C0,#F83A22"
            },
            "row_id": "row-1642069",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685612046",
            "player": "activity_access\/1642069"
        },
        {
            "nid": "1646984",
            "changed": "1685730937",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Cartographie avec Folium",
            "aid": "1646984",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1646984",
            "workflow": "0",
            "code": "2ba5-1646984",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-05-11T13:58:10",
            "tr_end": "2023-06-10T13:58:10",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1646984:0",
            "views_total": 68,
            "views_hidden": 0,
            "tags": {
                "nid": "1646984",
                "tids": "423016,463417",
                "names": "SNT,Corrig\u00e9",
                "colors": "#92E1C0,#F83A22"
            },
            "row_id": "row-1646984",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685730937",
            "player": "activity_access\/1646984"
        },
        {
            "nid": "1648152",
            "changed": "1685730390",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Cartographie avec Folium",
            "aid": "1648152",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1648152",
            "workflow": "0",
            "code": "5b6d-1648152",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-05-11T13:58:10",
            "tr_end": "2023-06-10T13:58:10",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1648152:0",
            "views_total": 83,
            "views_hidden": 0,
            "tags": {
                "nid": "1648152",
                "tids": "423012,463417",
                "names": "NSI,Corrig\u00e9",
                "colors": "#9A9CFF,#F83A22"
            },
            "row_id": "row-1648152",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685730390",
            "player": "activity_access\/1648152"
        },
        {
            "nid": "1648159",
            "changed": "1683841950",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Copie de Cartographie-Z avec Folium",
            "aid": "1648159",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1648159",
            "workflow": "0",
            "code": "737e-1648159",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-05-11T13:58:10",
            "tr_end": "2023-06-10T13:58:10",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1648159:0",
            "views_total": 0,
            "views_hidden": 0,
            "tags": {
                "nid": "1648159",
                "tids": "423012",
                "names": "NSI",
                "colors": "#9A9CFF"
            },
            "row_id": "row-1648159",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1683841950",
            "player": "activity_access\/1648159"
        },
        {
            "nid": "1678948",
            "changed": "1685094919",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Syst\u00e8mes d\u0027exploitation : introduction",
            "aid": "1678948",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1678948",
            "workflow": "0",
            "code": "ab4a-1678948",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-05-22T09:58:23",
            "tr_end": "2023-06-21T09:58:23",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1678948:0",
            "views_total": 58,
            "views_hidden": 0,
            "tags": [],
            "row_id": "row-1678948",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1685094919",
            "player": "activity_access\/1678948"
        },
        {
            "nid": "1729811",
            "changed": "1686303697",
            "said": null,
            "sa": "0",
            "own": "1",
            "actnodetype": "notebook_activity",
            "title": "Concours castor 2021",
            "aid": "1729811",
            "owner_id": null,
            "whoami": "cr",
            "own_aid": "1729811",
            "workflow": "0",
            "code": "dbae-1729811",
            "status_shared": "0",
            "status_web": "0",
            "status_clonable": "1",
            "access_tr_mode": "none",
            "tr_beg": "2023-06-05T12:08:12",
            "tr_end": "2023-07-05T12:08:12",
            "evaluation": "",
            "appreciation": "",
            "type": "notebook.python3",
            "bib": "1729811:0",
            "views_total": 78,
            "views_hidden": 0,
            "tags": {
                "nid": "1729811",
                "tids": "423016",
                "names": "SNT",
                "colors": "#92E1C0"
            },
            "row_id": "row-1729811",
            "mode": "N_O",
            "icon": "\/web\/modules\/custom\/capytale_activity\/src\/Activity\/logo\/logo_nb.svg",
            "provider": "hdf",
            "last_access": "1686303697",
            "player": "activity_access\/1729811"
        }
    ])
    return acti
}
